### ISSUE TITLE
how do i speed the bot up

### ISSUE THREAD

**Issue by mindfulObservant** [bababoyy/bababot#1]
i wanna go on anarchy so i can speed it up really fast

**Comment by bababoyisntapopularname** [comment]
Set your timeout (stored in localStorage) to 30-35
You can measure your speed by pressing "_".
About 35-50 is fine

**Comment by YTPDEMIN6475** [comment]
the bots will disable u trust me i tried

**Comment by bababoyy** [comment]
disable occurs when you're going too fast
I'll increase the default timeout tho

**Comment by bababoyy** [comment]
Use "Set timeout" extension
Timeout is in miliseconds so you can make your timeout the same as cooldown in miliseconds
