### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by TrashPossum** [bababoyy/bababot#5]
It just lags your game until you hit stop, and if it does do something then it ignores 99% of pixels

**Comment by TrashPossum** [comment]
> Avoid using extensions if you have a low resource pc. Try updating as you didn't specify any version you used. Try to avoid using fill for large areas as it's still not on Worker's thread. If your problem still exists, please send a screenshot of your Devtools' Console tab.

I am on the latest version (3.51 as of writing), the size of the area i'm trying to bot doesn't impact anything. No matter the type of extension i use, timeout amount, it doesn't do anything besides lag the website. On the occasion that it does place pixels, they are in a random spread out area, not creating an image at all. I have a fairly powerful PC also. [As for the "Devtools' Console tab", I do not know how to open that.]

**Comment by bababoyy** [comment]
https://developer.chrome.com/docs/devtools/console/
This is the documentation for opening console.
Please send a screenshot of console (with full content) when you open it.

**Comment by bababoyy** [comment]
Also can you tell me the steps you do while botting?

**Comment by bababoyy** [comment]
Closed as inactive
You're welcome to open it if you still have issues after updating
