### ISSUE TITLE
Bot doesn't paint 

### ISSUE THREAD

**Issue by Muskixd** [bababoyy/bababot#6]
Everything is ok with UI and all but when I press the 'start botting' button, it doesnt paint and it lags for doing nothing

**Comment by bababoyy** [comment]
Try refreshing page and if it still doesn't work please send me a screenshot of DevTools' console tab.
If you don't know how to open it please read https://developer.chrome.com/docs/devtools/open/ .

**Comment by Muskixd** [comment]
![image](https://user-images.githubusercontent.com/85181566/174456093-7e7862f6-1d4c-4d77-9358-e389d8263c00.png)

**Comment by bababoyy** [comment]
Well I can't see any problems here.
Did you tried botting before taking this screenshot?

**Comment by Muskixd** [comment]
I did

**Comment by bababoyy** [comment]
Updated protect event handler as it prevented pixelating.
Try updating

**Comment by bababoyy** [comment]
Closed as it should work now.
Open if you still have issues after updating.
